name: "Terraform destroy"
on:
  workflow_dispatch: 
    inputs:
      revisor:
        description: "Nome ou matricula do revisor"
        required: true
        type: string
jobs:
  terraform:
    name: "Terraform destroy - ${{ github.event.inputs.revisor }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./src_terraform
        run: terraform init -backend-config="key=${{ secrets.AWS_BUCKET_KEY}}" -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}"

      - name: Terraform destroy
        working-directory: ./src_terraform
        run: terraform destroy --auto-approve
        env:
            TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            TF_VAR_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}